sudo: false
language: haxe
os:
  - linux
  # - osx
haxe:
  - "3.2.1"
  - "3.4.0"
  - development
install:
  - haxelib install travix
  - haxelib run travix install
script:
  - haxelib run travix node
